### PR TITLE
Provide methods to disassemble signatures in JWS

### PR DESCRIPTION
**Pull request by stevvooe**
This adds (*JSONSignature).Signatures and modifies NewJSONSignature to allow working with individual signature blobs. The blobs can be pulled off of a signature, stored separately then merged back together. The signatures are transported as byte slices. This should support the changes required in docker/distribution#25.

This change also stabilizes the order in which signatures are written to json when multiple signatures are present. The signatures are sorted by key id then the actual signature bytes.

To simplify the code, some pointer type fields have been removed where it makes sense. Doing so should reduce the number of scattered heap allocations and simplify areas where we copy into a struct.

### CODE REVIEW

**Comment by dmp42** [comment]
LGTM

**Comment by dmcgowan** [comment]
Not fond of the update to NewJSONSignature but don't really think its worth getting caught up on if it doesn't break existing uses.

LGTM

**Comment by jlhawn** [comment]
LGTM

**Comment by stevvooe** [comment]
@dmcgowan I don't like it either.

We probably need to re-vamp the public API to support these use cases now that we have a better handle over them.

**Pull request merged**
