### PR TITLE
Add deprecation warning

### PR DESCRIPTION
**Pull request by thaJeztah**
per discussion on https://github.com/docker/libtrust/issues/55#issuecomment-230529319

### CODE REVIEW

**Comment by diogomonica** [comment]
LGTM

**Comment by thaJeztah** [comment]
ping @dmcgowan ptal

**Comment by dmcgowan** [comment]
Preferred waiting until we had some migration but I suppose the language is suitable for the current state.

LGTM

**Comment by thaJeztah** [comment]
oh, thanks! yeah, makes sense, but I think it doesn't hurt to have a notice at least

**Pull request merged**
